# TUGAS PERTEMUAN 2
## Nama : Eben Ezer Obed M
## NIM  : 20210801424

## SOAL 1

In [1]:
nama = "Eben Ezer Obed M"
nim = "20210801424"
jurusan = "Teknik Informatika"

print("DATA DIRI")
print("Nama : ", nama)
print("NIM : ", nim)
print("Jurusan : ", jurusan)

DATA DIRI
Nama :  Eben Ezer Obed M
NIM :  20210801424
Jurusan :  Teknik Informatika


## SOAL 2

In [2]:
matriksC= [[1,2,3],[4,5,6]]
print(matriksC)

[[1, 2, 3], [4, 5, 6]]


## SOAL 3

In [3]:
matriks = [[2,2],[2,2],[2,2]]
print(matriks)

[[2, 2], [2, 2], [2, 2]]


## SOAL 4

In [4]:
import numpy as np

## SOAL 5

In [5]:
from numpy import *
matriks = range(32)
matriks = reshape(matriks, (4,8))
print(matriks)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


## SOAL 6

In [6]:
import numpy as np
from numpy import *

matriks = np.random.randint(1,5,(3,30))
print(matriks)

[[1 3 4 1 4 4 1 1 1 3 3 3 3 1 1 2 4 1 1 4 2 2 4 2 1 2 1 1 1 4]
 [4 4 3 3 1 1 4 4 3 3 2 3 4 4 1 4 2 1 4 2 3 3 3 3 2 1 1 1 4 4]
 [1 1 4 4 3 3 3 4 1 4 2 1 3 3 2 4 1 4 4 3 2 4 2 1 2 3 3 4 1 4]]
